name: Production

on:
  push:
    branches: main

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    permissions:
      id-token: write
      contents: read
    with:
      environment: prod
  
